services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-backend
      - angular-frontend
    networks:
      - fvp_net

networks:
  fvp_net:
    driver: bridge