FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y make && apt-get clean

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY . /app

RUN rm -f /app/.env
