version: '3'
services:
  fastapi-backend:
    container_name: fastapi-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${POSTGRES_DATABASE_URL}
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env.production
    networks:
      - fvp_net
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

networks:
  fvp_net:
    driver: bridge
