services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fvp_net

  fastapi-backend:
    container_name: fastapi-backend
    build:
      context: ./backend  # Modificado
      dockerfile: Dockerfile
    ports:
      - "${FAST_API_PORT}:${FAST_API_PORT}"
    volumes:
      - ./backend:/app  # Modificado
    environment:
      - DATABASE_URL=${POSTGRES_DATABASE_URL}
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres_db
    networks:
      - fvp_net
    command: >
      uvicorn app.main:app --host ${HOST} --port ${FAST_API_PORT} --reload

volumes:
  postgres_data:

networks:
  fvp_net:
    driver: bridge