"""Add fund and transaction models

Revision ID: 2fa76e10bfed
Revises: 4e111108400a
Create Date: 2024-10-22 19:20:25.375250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fa76e10bfed'
down_revision: Union[str, None] = '4e111108400a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('minimum_amount', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_id'), 'funds', ['id'], unique=False)
    op.create_index(op.f('ix_funds_name'), 'funds', ['name'], unique=False)
    op.create_table('transactions',
    sa.Column('type', sa.Enum('SUBSCRIPTION', 'CANCELLATION', name='transactiontype'), nullable=False),
    sa.Column('fund_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_funds_name'), table_name='funds')
    op.drop_index(op.f('ix_funds_id'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
