"""Add unique constraint to fund name

Revision ID: 938272616394
Revises: 6c5129f1b989
Create Date: 2024-10-23 20:02:02.605579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938272616394'
down_revision: Union[str, None] = '6c5129f1b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_fund_name', 'funds', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_fund_name', 'funds', type_='unique')
    # ### end Alembic commands ###
